apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: b9rkaff8f-python
  janus-idp.io/tekton: b9rkaff8f-python
  backstage.io/kubernetes-id: b9rkaff8f-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: b9rkaff8f-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
